server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka