server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      # https://cloud.spring.io/spring-cloud-gateway/reference/html/
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - name: Path
              args:
                patterns: /admin/**
          filters:
            - name: RewritePath
              args:
                regexp: /admin/?(?<segment>.*)
                replacement: /$\{segment}
            - name: RequestSize
              args:
                maxSize: 5000000
            - name: LoggingGatewayFilter
              args:
                preLogger: true
                postLogger: true
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 1
                  requestedTokens: 1
                # key-resolver: "#{@myKeyResolver}"
          metadata:
            response-timeout: 200
            connect-timeout: 200
      redis-rate-limiter:
        include-headers: false
      x-forwarded:
        for-enabled: false
        host-enabled: false
        port-enabled: false
        proto-enabled: false
        prefix-enabled: false
      loadbalancer:
        use404: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
#      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
