server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  application:
    name: gateway
  profiles:
    active: dev
  messages:
    basename: messages
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - name: Path
              args:
                patterns: /auth/**
          filters:
            - name: LogFilter
            - name: RewritePath
              args:
                regexp: /auth/?(?<segment>.*)
                replacement: /$\{segment}
            - name: RequestSize
              args:
                maxSize: 5000000
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 5
                  burstCapacity: 5
                  requestedTokens: 1
                key-resolver: "#{@myKeyResolver}"
      redis-rate-limiter:
        include-headers: false
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      x-forwarded:
        for-enabled: false
        host-enabled: false
        port-enabled: false
        proto-enabled: false
        prefix-enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #      password: ENC(vs80g6g8RPF/BSJqw0ONpT7rvXgeri0SMZ/PszCK0O4V384HLZPICWdp) # redis-password
      time-to-live: 3600000
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example?serverTimezone=Asia/Seoul
    username: my
    password: 1234
    properties:
      schema: temp
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 60000
      max-lifetime: 180000
      max-create-connection-time: 2s
  security:
    user:
      password: 1234

hibernate:
  cache:
    use-second-level-cache: true

service:
  jwt:
    secret-key: U7cCRvJM16pFZ-vyWj3Z3liUfymmiNazsB7fCr8Bas8
    access:
      expiration: 3600000
  api:
    base-url:
      auth: http://localhost:8082/auth # lb://AUTH-SERVICE/auth
