server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  messages:
    basename: messages

  datasource:
    url: jdbc:postgresql://localhost:5432/example?serverTimezone=Asia/Seoul
    username: my
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: temp
        show-sql: true
        connection:
          character-encoding: UTF-8
          use-unicode: true
