# current
spring:
  profiles:
    active: local

---
# local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8761
eureka:
  instance:
    hostname: localhost

---
# dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: ${DISCOVERY_PORT}
eureka:
  instance:
    hostname: ${DISCOVERY_HOST}

---
# common
spring:
  application:
    name: discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
